// leaguesData.ts
import { LeaguesData } from '@/types/types'; // Ensure this path is correct based on your structure

export const leaguesData: LeaguesData = {
    get: "leagues",
    parameters: {},
    errors: null,
    results: 831,
    paging: {
        current: 1,
        total: 1,
    },
    response: [
        {
            id: 4,
            name: "Euro Championship",
            type: "Cup",
            logo: "https://media.api-sports.io/football/leagues/4.png",
            country: {
                name: "World",
                code: null,
                flag: null,
            },
            seasons: [
                {
                    year: 2008,
                    start: "2008-06-07",
                    end: "2008-06-29",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2012,
                    start: "2012-06-08",
                    end: "2012-07-01",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2016,
                    start: "2016-06-10",
                    end: "2016-07-10",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2020,
                    start: "2019-03-21",
                    end: "2021-06-23",
                    current: true,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: true,
                        predictions: true,
                        odds: true,
                    },
                },
            ],
        },
        {
            id: 61,
            name: "Ligue 1",
            type: "League",
            logo: "https://media.api-sports.io/football/leagues/61.png",
            country: {
                name: "France",
                code: "FR",
                flag: "https://media.api-sports.io/flags/fr.svg",
            },
            seasons: [
                {
                    year: 2010,
                    start: "2010-08-07",
                    end: "2011-05-29",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2011,
                    start: "2011-08-06",
                    end: "2012-05-20",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2012,
                    start: "2012-08-10",
                    end: "2013-05-26",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2013,
                    start: "2013-08-09",
                    end: "2014-05-17",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2014,
                    start: "2014-08-08",
                    end: "2015-05-23",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2015,
                    start: "2015-08-07",
                    end: "2016-05-14",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2016,
                    start: "2016-08-12",
                    end: "2017-05-20",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2017,
                    start: "2017-08-04",
                    end: "2018-05-19",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2018,
                    start: "2018-08-10",
                    end: "2019-05-24",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2019,
                    start: "2019-08-09",
                    end: "2020-05-23",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2020,
                    start: "2020-08-21",
                    end: "2021-05-23",
                    current: true,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: true,
                        predictions: true,
                        odds: true,
                    },
                },
            ],
        },
        {
            id: 39,
            name: "Serie A",
            type: "League",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            country: {
                name: "Italy",
                code: "IT",
                flag: "https://media.api-sports.io/flags/it.svg",
            },
            seasons: [
                {
                    year: 2010,
                    start: "2010-08-14",
                    end: "2011-05-22",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2011,
                    start: "2011-08-27",
                    end: "2012-05-13",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2012,
                    start: "2012-08-25",
                    end: "2013-05-26",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2013,
                    start: "2013-08-24",
                    end: "2014-05-18",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2014,
                    start: "2014-08-30",
                    end: "2015-05-31",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2015,
                    start: "2015-08-22",
                    end: "2016-05-15",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2016,
                    start: "2016-08-20",
                    end: "2017-05-28",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2017,
                    start: "2017-08-19",
                    end: "2018-05-20",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2018,
                    start: "2018-08-18",
                    end: "2019-05-26",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2019,
                    start: "2019-08-24",
                    end: "2020-08-02",
                    current: true,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: true,
                        predictions: true,
                        odds: true,
                    },
                },
            ],
        },
        {
            id: 140,
            name: "Bundesliga",
            type: "League",
            logo: "https://media.api-sports.io/football/leagues/140.png",
            country: {
                name: "Germany",
                code: "DE",
                flag: "https://media.api-sports.io/flags/de.svg",
            },
            seasons: [
                {
                    year: 2010,
                    start: "2010-08-20",
                    end: "2011-05-14",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2011,
                    start: "2011-08-05",
                    end: "2012-05-12",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2012,
                    start: "2012-08-24",
                    end: "2013-05-18",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2013,
                    start: "2013-08-09",
                    end: "2014-05-17",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2014,
                    start: "2014-08-22",
                    end: "2015-05-23",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2015,
                    start: "2015-08-14",
                    end: "2016-05-14",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2016,
                    start: "2016-08-26",
                    end: "2017-05-20",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2017,
                    start: "2017-08-18",
                    end: "2018-05-12",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2018,
                    start: "2018-08-24",
                    end: "2019-05-18",
                    current: false,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: false,
                        predictions: true,
                        odds: false,
                    },
                },
                {
                    year: 2019,
                    start: "2019-08-16",
                    end: "2020-06-27",
                    current: true,
                    coverage: {
                        fixtures: true,
                        standings: true,
                        players: true,
                        top_scorers: true,
                        top_assists: true,
                        top_cards: true,
                        injuries: true,
                        predictions: true,
                        odds: true,
                    },
                },
            ],
        },
    ],
};
